apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  endpoint_url: aHR0cDovLzEwLjMuMjU0LjUxOjgwCg==
  access_key: YWRtaW4K
  secret_key: TUphYmJveEJHUwo=
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-credentials
type: Opaque
data:
  tracking_uri: aHR0cDovLzM0Ljg3LjYyLjIyOjgwCg==
  registered_model: bW9kZWxzOi9nb2Vtb3Rpb25fTUxQLzEK
  artifacts_destination: bWxmbG93Cg==