FROM python:3.11-slim

LABEL maintainer="duongng2911"
LABEL organization="nrl"

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./serving /app

EXPOSE 8080

RUN pip install -r requirements.txt --no-cache-dir

CMD [ "python", "mlp.py" ]