version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
      # target: builder
    container_name: api
    # platform: linux/amd64
    ports:
      - 8000:3000 # host port : api port
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_REGISTERED_MODEL=${MLFLOW_REGISTERED_MODEL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ENDPOINT_URL=${MINIO_ENDPOINT_URL}
      - PROMETHEUS_IP=${PROMETHEUS_IP}
      - JAEGER_IP=${JAEGER_IP}
      - JAEGER_PORT=${JAEGER_PORT}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}